default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_CONTENT'],
      is_key_content_base64: false
    )

    import_certificate(
      certificate_path: 'cert.p12',
      certificate_password: '',
      keychain_name: 'login.keychain'
    ) rescue nil

    install_provisioning_profile(
      path: 'GenomaFlow.mobileprovision'
    ) rescue nil

    build_app(
      workspace: 'App/App.xcworkspace',
      scheme: 'App',
      export_method: 'app-store',
      output_directory: './build'
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
