default_platform(:android)

platform :android do
  lane :supply do
    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['GOOGLE_PLAY_JSON_KEY_DATA'],
      package_name: 'com.genomaflow.app',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
